config/routes.rb
Rails.application.routes.draw do
  resources :messages
  # Admin panel
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  root :to => 'properties#index'
  resources :properties
  resources :users
  #resources :sessions, only: [:new, :create, :destroy]
  match '/login', to: 'sessions#new', via: :get
  match '/login_create', to: 'sessions#create', via: :post
  #match '/logout', to: 'sessions#destroy', via: :delete
  match '/logout', to: 'sessions#destroy', via: :get
  get 'about', to: 'pages#about'

  get 'contact', to: 'messages#contact'

  resources :appointments

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  before_save { |user| user.email=user.email.downcase }
  # before_save :create_session_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  def self.create_user!(user_hash)
    #validats user_hash[:uer_id], :uniqueness,{:message => "Sorry, this user-id is taken. Try again."}
    user_hash[:session_token] = SecureRandom.base64
    create!(user_hash)
  end

# private
#   def create_session_token
#     self.session_token= SecureRandom.urlsafe_base64
#   end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :set_current_user

  # Display all saved Users
  #
  def index
    @users = User.all  # Return all Users
  end

  # Display one User
  #
  def show
    email = user_params[:email] # retrieve User ID from URI route
    @user = User.find_by_email email  # Find User by ID and return the User
    # will render app/views/users/show.<extension> by default
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def new
    # default: render 'new' template
  end

  def create
    if User.find_by_email(user_params[:email])!=nil
      flash[:notice] = "Sorry, this user-email is taken. Try again."
      redirect_to new_user_path, :method=>:get
    else
      @user = User.create_user!(user_params)
      flash[:notice] = "Welcome <#{@user.name}>. Your account was successfully created."
      #redirect_to movies_path
      redirect_to login_path, :method=>:get
    end

  end
end

app/views/users/index.html.haml
-#  This file is app/views/movies/index.html.haml
%h1 User Profile

.card.mt-3
  .card-header
    .p.font-weight-bold Information
  .card-body
    .row.text-center
      %table.table.table-hover
        %tbody
          %tr
            %td
              .p.font-weight-bold  Name
            %td
              %p #{@current_user.name}
          %tr
            %td
              .p.font-weight-bold  Email
            %td #{@current_user.email}
          %tr
            %td
              .p.font-weight-bold  Created At
            %td{:colspan => "2"} #{@current_user.created_at}
          %tr
            %td
              .p.font-weight-bold  Updated At
            %td{:colspan => "2"}
              #{@current_user.updated_at}

app/views/users/new.html.haml
-unless @user == nil
  -if @user.errors.any?
    %ul
    -@user.errors.full_messages.each do |msg|
      %li #{msg}

.container.h-auto
  .row
    %div.col-md-12.min-vh-100.d-flex.flex-column.justify-content-center
      .row
        %div.col-lg-6.col-md-8.mx-auto
          .card
            .card-header.text-center
              %h3 Signup
            .card-body.text-center
              = form_tag users_path do
                = label :user, :name, 'Name'
                = text_field :user, 'name', :id=> 'signupUser'
                %p
                = label :user, :email, 'EMail'
                = email_field :user, 'email', :id=> 'signupEmail'
                %p
                = label :user, :password, 'Password'
                = password_field :user, 'password', :id=> 'signupPassword'
                %p
                = label :user, :password_confirmation, 'Confirm Your Password'
                = password_field :user, 'password_confirmation', :id=> 'signupPasswordConfirmaiton'
                %p
                = submit_tag 'Create my account', :id=> 'signupCreate'

app/views/users/show.html.haml
%h2 Profile for #{@user.name}

%ul#details
  %li
    name:
    = @user.name
  %li
    e-mail:
    = @user.email

=link_to 'Back to home page', properties_path