config/routes.rb
Rails.application.routes.draw do
  resources :messages
  # Admin panel
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  root :to => 'properties#index'
  resources :properties
  resources :users
  #resources :sessions, only: [:new, :create, :destroy]
  match '/login', to: 'sessions#new', via: :get
  match '/login_create', to: 'sessions#create', via: :post
  #match '/logout', to: 'sessions#destroy', via: :delete
  match '/logout', to: 'sessions#destroy', via: :get
  get 'about', to: 'pages#about'

  get 'contact', to: 'messages#contact'

  resources :appointments

end

app/models/property.rb
class Property < ActiveRecord::Base
  validates :address, presence: true
  validates :bedrooms, numericality: { only_integer: true }
  validates :bathrooms, numericality: { only_integer: true }
  validates :price, numericality: true
  validates :sqft, numericality: { allow_blank: true }
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_filter :set_current_user

  def new
    # default: render 'new' template
  end

  def show
    id = params[:id] # retrieve movie ID from URI route
    @property = Property.find(id)
  end

  def index
    @properties = Property.all
  end

end

app/views/properties/index.html.haml
-#  This file is app/views/properties/index.html.haml
%head
  = stylesheet_link_tag 'index', 'media' => 'all', 'data-turbolinks-track' => true
  = stylesheet_link_tag 'application', 'media' => 'all', 'data-turbolinks-track' => true
  %script{:crossorigin => "anonymous", :src => "https://kit.fontawesome.com/a73ffde100.js"}

%body
  -#.nav-bar
  -#= render "shared/nav"

  .container.text-dark.shadow
  - @properties.each_slice(4) do |four_houses|
    %div.row.justify-content-around
      - four_houses.each do |house|
        %a.custom-card{:href => property_path(house)}
          .card.text-center.text-capitalize.m-4.shadow{:style => "width: 18rem;"}
            %img.card-img-top#property-preview-img{:src => house.url}/
            .card-header
              .p #{house.address}
            %ul.list-group.list-group-flush
              %li.list-group-item #{number_to_currency(house.price, :precision => 0)} per Month
              %table.table.table.table-light
                %thead
                  %tr
                    %th.font-weight-bold.bg-light{:scope => "col"} Beds
                    %th.font-weight-bold.bg-light{:scope => "col"} Baths
                    %th.font-weight-bold.bg-light{:scope => "col"} Sqft
                %tbody
                  %tr
                    %th.font-weight-light{:scope => "row"} #{house.bedrooms}
                    %td.font-weight-light #{house.bathrooms}
                    %td.font-weight-light #{house.sqft}


        -#%div.row.justify-content-between
        -#      %span.border-right.border-primary.p-2
        -#        .p 1 bds
        -#      %span.border-right.border-secondary.p-2
        -#        .p 2 baths
        -#      %span.p-2
        -#        .p 1200 sqft

            -#$#{house.price} / month
          -#%ul.list-group.list-group-flush
          -#  %li.list-group-item Cras justo odio
          -#  %li.list-group-item Dapibus ac facilisis in
          -#  %li.list-group-item Vestibulum at eros
          .card-body
            %a.card-link{:href => property_path(house)} More Info
            %a.card-link{:href => "#"} Another link
          %p.card-text
            %small.text-muted Created #{ ((Time.now - house.created_at).to_i / 3600).to_i } day(s) ago

        -#%div.col-sm-4.col-md-3.text-center
        -#  %div.thumbnail
        -#    %img.image{:src=>house.url}
        -#    .div.address
        -#      %i.fas.fa-home
        -#      #{house.address}
        -#    .div.price
        -#      %i.fas.fa-dollar-sign
        -#      #{house.price}/mo
        -#    %div
        -#      =button_to 'More Info', property_path(house), :method => :get


-#%table#properties
-#  - @properties.each do |object|
-#    %tr
-#      %td
-#      -#%td{:align => "center", :valign => "center"}
-#      %img{:src => object.url}/
-#      %br/
-#      #{object.price}
-#      %br/
-#      #{object.address}
-#      %br/
-#      #{object.sqft}
      -#=button_to 'More Info', properties_path

      -#%td
      -#%div{:class=>'column'}
      -#  %img{:src=>object.url}
      -#  %div{:class=>'price'}
      -#    #{object.price}
      -#  %div{:class=>'address'}
      -#    #{object.address}
      -#  %div{:class=>'area'}
      -#    #{object.sqft}
      -#  %div{:class=>"moreinfo"}

app/views/properties/show.html.haml
-# in app/views/properties/show.html.haml
%head

  = stylesheet_link_tag 'application', 'media' => 'all', 'data-turbolinks-track' => true
  %title Property Details

-#.nav-bar
-#  = render "shared/nav"


.container.justify-content-center
  .card.mt-3.mb-3
    .row
      .col-4.text-center
        .div.pb-3
        .h1 Property Details
        .div.pb-3
          .span.font-weight-bold Address
          #{@property.address}
        .p.pb-3
          .span.font-weight-bold Price
          $ #{@property.price}/mo
        .p.pb-3
          .span.font-weight-bold Sqft
          #{@property.sqft} sqft
        .p.pb-3
          .span.font-weight-bold Bedrooms
          #{@property.bedrooms}
        .p.pb-3
          %a
            =button_to 'Back to Home Page', properties_path, :method => :get
        .p.pb-3
          %a
            =button_to 'Schedule Visit', new_message_path, :method => :get
      .col-8
        %img.image#test-img{:src=>@property.url, :href => @property.url}
  .card.mt-3
    .card-header
      .p.font-weight-bold Additional Details
    .card-body
      .row.text-center
        %table.table.table-hover
          %tbody
            %tr
              %td
                .p.font-weight-bold  Address
              %td
                %p #{@property.address}
            %tr
              %td
                .p.font-weight-bold  Price
              %td $ #{@property.price} / month
            %tr
              %td
                .p.font-weight-bold  Sqft
              %td{:colspan => "2"} #{@property.sqft} sqft
            %tr
              %td
                .p.font-weight-bold  Bedrooms
              %td{:colspan => "2"}
                #{@property.bedrooms}